---
# tasks file for ldap-oauth

- name: Create CA cert cofigmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'ca-cert-cfgmap.j2') }}"

- name: Create LDAP bind password secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'bind-password-secret.j2') }}"

- name: Create LDAP oauth config
  k8s:
    state: present
    definition: "{{ lookup('template', 'ldap-oauth-config.j2') }}"

# TODO: remove this later. put in here for debugging
- debug:
    msg: "{{ ldap_url }}{{ filter_groups }}"
